[mysqld]
basedir="C:\\Users\\mitchell\\Projects\\BLIS4\\server\\MySQL"
bind-address=127.0.0.1
datadir="C:\\Users\\mitchell\\Projects\\BLIS4\\dbdir"
#default-character-set=latin1
#default-collation=latin1_general_ci
log-error="C:\\Users\\mitchell\\Projects\\BLIS4\\server\\tmp\\log.err"
pid-file="C:\\Users\\mitchell\\Projects\\BLIS4\\server\\tmp\\mysql.pid"
#slow query log#=
tmpdir="C:\\Users\\mitchell\\Projects\\BLIS4\\server\\tmp"
port=7199
#set-variable=key_buffer=16M

# Uncomment the following if you are using InnoDB tables
innodb_data_home_dir = "C:\\Users\\mitchell\\Projects\\BLIS4\\dbdir"
innodb_data_file_path = ibdata1:10M:autoextend
innodb_log_group_home_dir = "C:\\Users\\mitchell\\Projects\\BLIS4\\dbdir"
#innodb_log_arch_dir = "C:\\Users\\mitchell\\Projects\\BLIS4\\dbdir"
innodb_buffer_pool_size = 256M
#innodb_additional_mem_pool_size = 20M
#innodb_log_file_size = 64M
innodb_log_buffer_size = 8M
innodb_flush_log_at_trx_commit = 1
innodb_lock_wait_timeout = 50
innodb_file_per_table = 1
